import Foundation
import Observation

enum AuthStatus: Equatable {
    case unknown
    case needsApiKey
    case needsLogin
    case signedIn
}

/// Manages every connected Steam account. The first account still goes
/// through the classic "enter API key → sign in with Steam" onboarding gate
/// (driven by `status`) — an OpenID sign-in alone can't replace the manual
/// key step since Steam Web API keys have no OAuth equivalent and must be
/// generated by the user on steamcommunity.com/dev/apikey. Once at least
/// one account is connected, further accounts are added in-place via
/// `addAccount` without ever touching `status` again. Ports the Flutter
/// app's AuthState 1:1.
@Observable
final class AuthViewModel {
    private let webAPI = SteamWebAPI()
    private let openID = SteamOpenIDService()
    private static let accountsKey = "steam_accounts_v1"

    var status: AuthStatus = .unknown
    var accounts: [SteamAccount] = []
    var errorMessage: String?
    var isSigningIn = false

    private var pendingApiKey: String?

    var primaryAccount: SteamAccount? { accounts.first }

    func restore() {
        accounts = KeychainStore.getCodable([SteamAccount].self, forKey: Self.accountsKey) ?? []
        status = accounts.isEmpty ? .needsApiKey : .signedIn
    }

    /// Step 1 of the first-account onboarding gate: stash the API key and
    /// move on to the "sign in with Steam" screen.
    func saveApiKey(_ key: String) {
        pendingApiKey = key
        status = .needsLogin
    }

    /// Cancels the pending "enter API key" step so the user can re-enter a
    /// different key.
    func removeApiKey() {
        pendingApiKey = nil
        status = .needsApiKey
    }

    /// Step 2 of the first-account onboarding gate.
    func signInWithSteam() async {
        guard let key = pendingApiKey, !key.isEmpty else {
            status = .needsApiKey
            return
        }
        let error = await performSignIn(apiKey: key)
        if error == nil {
            pendingApiKey = nil
            status = .signedIn
        }
    }

    /// Adds an additional Steam account once already signed in (used from
    /// Settings in a later phase). Returns an error message on failure, or
    /// nil on success — `status` is left untouched.
    @discardableResult
    func addAccount(apiKey: String) async -> String? {
        await performSignIn(apiKey: apiKey)
    }

    func removeAccount(steamId: String) {
        accounts.removeAll { $0.steamId == steamId }
        KeychainStore.setCodable(accounts, forKey: Self.accountsKey)
        if accounts.isEmpty { status = .needsApiKey }
    }

    /// Disconnects every Steam account.
    func signOut() {
        accounts = []
        pendingApiKey = nil
        KeychainStore.delete(Self.accountsKey)
        status = .needsApiKey
    }

    private func performSignIn(apiKey: String) async -> String? {
        isSigningIn = true
        errorMessage = nil
        defer { isSigningIn = false }

        do {
            let steamId = try await openID.signIn()
            if accounts.contains(where: { $0.steamId == steamId }) {
                errorMessage = "Dieser Steam-Account ist bereits verbunden."
                return errorMessage
            }

            let summary = try await webAPI.getPlayerSummary(apiKey: apiKey, steamId: steamId)
            let account = SteamAccount(
                steamId: steamId,
                apiKey: apiKey,
                personaName: summary.personaName,
                avatarUrl: summary.avatarUrl
            )
            accounts.append(account)
            KeychainStore.setCodable(accounts, forKey: Self.accountsKey)
            return nil
        } catch {
            errorMessage = "Anmeldung fehlgeschlagen: \(error.localizedDescription)"
            return errorMessage
        }
    }
}
